// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceTaskStatusReducer from "../advance_task_status_reducer";
import CreateAutoTaskReducer from "../create_auto_task_reducer";
import CreateTaskReducer from "../create_task_reducer";
import SeedAutoTaskReducer from "../seed_auto_task_reducer";
import UpdateTaskContextReducer from "../update_task_context_reducer";

export type AdvanceTaskStatusParams = __Infer<typeof AdvanceTaskStatusReducer>;
export type CreateAutoTaskParams = __Infer<typeof CreateAutoTaskReducer>;
export type CreateTaskParams = __Infer<typeof CreateTaskReducer>;
export type SeedAutoTaskParams = __Infer<typeof SeedAutoTaskReducer>;
export type UpdateTaskContextParams = __Infer<typeof UpdateTaskContextReducer>;

