// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Task = __t.object("Task", {
  id: __t.u64(),
  title: __t.string(),
  status: __t.string(),
  source: __t.string(),
  commitHash: __t.option(__t.string()),
  context: __t.string(),
  createdAt: __t.timestamp(),
  authorIdentity: __t.identity(),
});
export type Task = __Infer<typeof Task>;

