// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  taskId: __t.u64().name("task_id"),
  taskTitle: __t.string().name("task_title"),
  previousStatus: __t.string().name("previous_status"),
  newStatus: __t.string().name("new_status"),
  aiResolved: __t.bool().name("ai_resolved"),
  reason: __t.string(),
  resolutionSource: __t.string().name("resolution_source"),
  commitHash: __t.option(__t.string()).name("commit_hash"),
  documentRefs: __t.array(__t.string()).name("document_refs"),
  createdAt: __t.timestamp().name("created_at"),
  actorIdentity: __t.identity().name("actor_identity"),
});
