// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  title: __t.string(),
  status: __t.string(),
  source: __t.string(),
  commitHash: __t.option(__t.string()).name("commit_hash"),
  context: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  authorIdentity: __t.identity().name("author_identity"),
  resolutionKind: __t.string().name("resolution_kind"),
  resolutionSource: __t.string().name("resolution_source"),
  resolutionContext: __t.string().name("resolution_context"),
  resolutionCommitHash: __t.string().name("resolution_commit_hash"),
  resolutionDocumentRefs: __t.array(__t.string()).name("resolution_document_refs"),
});
